force-app/main/default/objects/ChildcareFee__c/ChildcareFee__c.object-meta.xml
<CustomObject>
    <label>保育料</label>
    <nameField>
        <displayFormat>CF{YYYY}{MM}-{000}</displayFormat>
        <label>保育料名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChildcareFee__c/fields/Belongs__c.field-meta.xml
<CustomField>
    <fullName>Belongs__c</fullName>
    <formula>TEXT(ImportantNotes__r.Belongs__c)</formula>
    <label>所属</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChildcareFee__c/fields/ChildcareFee__c.field-meta.xml
<CustomField>
    <fullName>ChildcareFee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>保育料</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ChildcareFee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>園児</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>保育料</relationshipLabel>
    <relationshipName>ChildcareFee_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChildcareFee__c/fields/ImportantNotes__c.field-meta.xml
<CustomField>
    <fullName>ImportantNotes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>要録情報</label>
    <referenceTo>ImportantNotes__c</referenceTo>
    <relationshipLabel>保育料</relationshipLabel>
    <relationshipName>ChildcareFees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChildcareFee__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>月</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChildcareFee__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <formula>ImportantNotes__r.Number__c</formula>
    <label>園児番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChildcareFee__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>年</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
                <default>true</default>
                <label>2019</label>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Belongs__c.field-meta.xml
<CustomField>
    <fullName>Belongs__c</fullName>
    <label>所属</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>幼稚園部</fullName>
            </value>
            <value>
                <fullName>保育園部の標準時間</fullName>
            </value>
            <value>
                <fullName>保育園部の短時間</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>学級</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>★★ぐみ</fullName>
            </value>
            <value>
                <fullName>●●ぐみ</fullName>
            </value>
            <value>
                <fullName>▼▼ぐみ</fullName>
            </value>
            <value>
                <fullName>ゆり</fullName>
            </value>
            <value>
                <fullName>きく</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>園児番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <label>通園コース</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>犬１</fullName>
            </value>
            <value>
                <fullName>犬２</fullName>
            </value>
            <value>
                <fullName>ネコ１</fullName>
            </value>
            <value>
                <fullName>ネコ２</fullName>
            </value>
            <value>
                <fullName>ビーバー</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <formula>TEXT(Account.School__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>幼稚園</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/ImportantNotes__c.object-meta.xml
<CustomObject>
    <label>要録情報</label>
    <nameField>
        <displayFormat>IN{YYYY}/{MM}-{000}</displayFormat>
        <label>要録情報名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ImportantNotes__c/fields/BusDisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>BusDisplayOrder__c</fullName>
    <label>バス表示順</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>学級</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>みつば</fullName>
            </value>
            <value>
                <fullName>ふたば</fullName>
            </value>
            <value>
                <fullName>つぼみ</fullName>
            </value>
            <value>
                <fullName>あさがお</fullName>
            </value>
            <value>
                <fullName>すみれ</fullName>
            </value>
            <value>
                <fullName>たんぽぽ</fullName>
            </value>
            <value>
                <fullName>ばら</fullName>
            </value>
            <value>
                <fullName>さくら</fullName>
            </value>
            <value>
                <fullName>きく</fullName>
            </value>
            <value>
                <fullName>ゆり</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>園児</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>要録情報</relationshipLabel>
    <relationshipName>ImportantNotes_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>FiscalYear__c</fullName>
    <label>年度</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>園児番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <formula>TEXT(Contact__r.PassageRoute__c)</formula>
    <label>通園コース</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestImportantNotesAuto.cls
@isTest
public class TestImportantNotesAuto {
    // 登録時のテスト
    @isTest static void test_create1(){
        // テストデータ作成
        // 要録情報データ
        ImportantNotes__c insItn1 = CreateImportantNotes1();

        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.insert(insItn1, false);        
        Test.stopTest();
    }

    // 変更時のテスト
    @isTest static void test_update1(){
        // テストデータ作成
        // 要録情報データ
        ImportantNotes__c updItn1 = UpdateImportantNotes1();

        // テスト開始
        Test.startTest();
        Database.SaveResult result = Database.Update(updItn1, false);        
        Test.stopTest();
    }

    // 削除時のテスト
    @isTest static void test_delete1(){
        // テストデータ作成
        // 要録情報データ
        ImportantNotes__c dltItn1 = DeleteImportantNotes1();

        // テスト開始
        Test.startTest();
        delete(dltItn1);        
        Test.stopTest();
    }


    // 要録情報テストデータ作成
    private static ImportantNotes__c   CreateImportantNotes1(){
        // 園児データ作成
        Contact insCnt = CreateEnji();
        insert insCnt;
        String CNTID = insCnt.Id;

        // 要録情報データ作成
        ImportantNotes__c itn = new ImportantNotes__c(
            FiscalYear__c = '2019',
            School__c = '北広島わかば',
            Belongs__c = '幼稚園部',
            Number__c = '101',
            Class__c = 'ゆり',
            PassageRoute__c = '犬１',
            BusDisplayOrder__c = '101',
            Contact__c = CNTID
        );
        return itn;
    }

    // 要録情報テストデータ更新
    private static ImportantNotes__c   UpdateImportantNotes1(){
        // 園児データ作成
        Contact insCnt = CreateEnji();
        insert insCnt;
        String CNTID = insCnt.Id;

        // 要録情報データ作成
        ImportantNotes__c insItn = CreateImportantNotes1();
        insert insItn;
        String ITNID = insItn.Id;

        // -----------------------------------------------------------
        // 1秒ウェイト（更新が早いため）
        // -----------------------------------------------------------
        Long startTime = DateTime.now().getTime();
        Long finishTime = DateTime.now().getTime();
        while ((finishTime - startTime) < 1000) {
            finishTime = DateTime.now().getTime();
        }
        
        // 保育料データ削除
//        ChildcareFee__c delCf = [SELECT Id FROM ChildcareFee__c WHERE Year__c = '2019' AND Month__c = '12' AND ImportantNotes__c = :ITNID];
        LIST<ChildcareFee__c> delCf = [SELECT Id FROM ChildcareFee__c WHERE ImportantNotes__c = :ITNID];
System.debug('delCfdelCf　'+[SELECT Id FROM ChildcareFee__c WHERE ImportantNotes__c = :ITNID]);
        delete(delCf);
System.debug('delCfdelCf　'+[SELECT Id FROM ChildcareFee__c WHERE ImportantNotes__c = :ITNID]);

        // 要録情報データ更新
        ImportantNotes__c itn = new ImportantNotes__c(
            Id = ITNID,
            FiscalYear__c = '2019',
            School__c = '北広島わかば',
            Belongs__c = '保育園部の標準時間',
            Number__c = '101',
            Class__c = 'ゆり',
            PassageRoute__c = '犬１',
            BusDisplayOrder__c = '101',
            Contact__c = CNTID
        );
        return itn;
    }

    // 要録情報テストデータ削除
    private static ImportantNotes__c   DeleteImportantNotes1(){
        // 園児データ作成
        Contact insCnt = CreateEnji();
        insert insCnt;
        String CNTID = insCnt.Id;

        // 要録情報データ作成
        ImportantNotes__c insItn = CreateImportantNotes1();
        insert insItn;
        String ITNID = insItn.Id;

        ImportantNotes__c delItn = [SELECT Id FROM ImportantNotes__c WHERE Id = :ITNID];

        return delItn;
    }

    // 園児テストデータ作成
    private static Contact  CreateEnji(){
        
        // 保護者データ作成
		Account act = new Account (
            Name = 'テスト保護者'
        );
        insert act;
        String ACTID = act.Id;
        
        // データ作成
        Contact cnt = new contact(
            LastName = 'テスト園児',
            AccountId = ACTID
        );
        return cnt;
    }

}