force-app/main/default/objects/Account/fields/INReflectionTime__c.field-meta.xml
<CustomField>
    <fullName>INReflectionTime__c</fullName>
    <label>[システム]反映時間</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mail__c.field-meta.xml
<CustomField>
    <fullName>Mail__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>口座名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>AccountNumber__c</fullName>
    <label>口座番号</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AnotherAffiliation__c.field-meta.xml
<CustomField>
    <fullName>AnotherAffiliation__c</fullName>
    <label>所属の別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1号認定</fullName>
            </value>
            <value>
                <fullName>2号認定</fullName>
            </value>
            <value>
                <fullName>3号認定</fullName>
            </value>
            <value>
                <fullName>1号認定新2号</fullName>
            </value>
            <value>
                <fullName>1号認定（2歳児）</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <label>銀行名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Belongs__c.field-meta.xml
<CustomField>
    <fullName>Belongs__c</fullName>
    <label>所属</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>幼稚園部</fullName>
            </value>
            <value>
                <fullName>保育園部の標準時間</fullName>
            </value>
            <value>
                <fullName>保育園部の短時間</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Mail__c.field-meta.xml
<CustomField>
    <fullName>Mail__c</fullName>
    <formula>Account.Mail__c</formula>
    <label>メールアドレス</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>園児番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <label>通園コース</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>犬１</fullName>
            </value>
            <value>
                <fullName>犬２</fullName>
            </value>
            <value>
                <fullName>ネコ１</fullName>
            </value>
            <value>
                <fullName>ネコ２</fullName>
            </value>
            <value>
                <fullName>ビーバー</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <formula>TEXT(Account.School__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>幼稚園</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StoreNumber__c.field-meta.xml
<CustomField>
    <fullName>StoreNumber__c</fullName>
    <label>店番号</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/ImportantNotes__c.object-meta.xml
<CustomObject>
    <label>要録情報</label>
    <nameField>
        <displayFormat>IN{YYYY}/{MM}-{000}</displayFormat>
        <label>要録情報名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ImportantNotes__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <label>口座名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>AccountNumber__c</fullName>
    <label>口座番号</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/AnotherAffiliation__c.field-meta.xml
<CustomField>
    <fullName>AnotherAffiliation__c</fullName>
    <label>所属の別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AnotherAffiliation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <label>銀行名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>園児</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>要録情報</relationshipLabel>
    <relationshipName>ImportantNotes_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Mail__c.field-meta.xml
<CustomField>
    <fullName>Mail__c</fullName>
    <label>メール</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>園児番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <formula>TEXT(Contact__r.PassageRoute__c)</formula>
    <label>通園コース</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/StoreNumber__c.field-meta.xml
<CustomField>
    <fullName>StoreNumber__c</fullName>
    <label>店番号</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ImportantNotesToEnjiController.cls
public without sharing class ImportantNotesToEnjiController {

    // 要録情報OBJからボタンで呼び出し
    @AuraEnabled
    public static String EnjiUpdate(ID ImportantNotesid) {

        // 要録情報データを検索
        // ID、関連園児ID、幼稚園、所属、所属の別、園児番号、通園コース、メール
        // 銀行名、店番号、口座番号、口座名
        List<ImportantNotes__c> ImportantNotesList = [SELECT Id, Contact__c, School__c, Mail__c,
                                                                                                            Belongs__c, AnotherAffiliation__c,
                                                                                                            Number__c, PassageRoute__c,
                                                                                                            BankName__c, StoreNumber__c,
                                                                                                            AccountNumber__c, AccountName__c
                                                                                                            FROM ImportantNotes__c 
                                                                                                            WHERE Id = :ImportantNotesid];

        // 要録情報データなし
        if(ImportantNotesList.size() == 0){
            // データなしメッセージ
            return '要録情報データがありません！';
        }

        // 要録情報データを取得
        ImportantNotes__c ImportantNotes = ImportantNotesList.get(0);
System.debug('ImportantNotes　'+ImportantNotes);
System.debug('ImportantNotes.Mail__c　'+ImportantNotes.Mail__c);

        // 園児OBJ
        List<Contact> ContactTMP = new List<Contact>();

        // 園児OBJを更新情報
        // 幼稚園、所属、所属の別、園児番号、通園コース、メール
        // 銀行名、店番号、口座番号、口座名
        ContactTMP.add(new Contact(
                                                            Id = ImportantNotes.Contact__c,
															Email = ImportantNotes.Mail__c,
                                                            School__c = ImportantNotes.School__c,
                                                            Belongs__c = ImportantNotes.Belongs__c,
                                                            AnotherAffiliation__c = ImportantNotes.AnotherAffiliation__c,
                                                            Number__c = ImportantNotes.Number__c,
                                                            PassageRoute__c = ImportantNotes.PassageRoute__c,
                                                            BankName__c = ImportantNotes.BankName__c,
                                                            StoreNumber__c = ImportantNotes.StoreNumber__c,
                                                            AccountNumber__c = ImportantNotes.AccountNumber__c,
                                                            AccountName__c = ImportantNotes.AccountName__c,
                                                            INReflectionTime__c = Datetime.now()
                                                )
        );
        
        // 園児OBJデータ更新
        if (ContactTMP.size() > 0) {
            try{
System.debug('update ContactTMP　'+ContactTMP);
                update ContactTMP;
            }catch(DmlException e){
                System.debug('ImportantNotes__c 園児OBJの更新失敗');
                Integer errNum = e.getNumDml();
                for(Integer i = 0; i < errNum; i++){
                    ContactTMP.get(e.getDmlIndex(i)).addError('園児データ更新時にエラーが発生しました'+e.getDmlMessage(i));
                }
            }
        }

        // 保護者データの更新
        // 園児データを検索
        List<Contact > ContactList = [SELECT Id, AccountId FROM Contact  
                                                                               WHERE Id = :ImportantNotes.Contact__c];
 
        // 園児データあり
        if(ContactList.size() > 0){
            // レコード取得
            Contact  ContactREC = ContactList.get(0);

            // 保護者IDがNULLでない場合、保護者OBJデータを更新
            if(ContactREC.AccountId != null){
                // 保護者OBJ
                List<Account> AccountTMP = new List<Account>();

                // 保護者OBJを更新情報
                // 幼稚園
                AccountTMP.add(new Account(
                                                            Id = ContactREC.AccountId,
                                                            School__c = ImportantNotes.School__c,
															Mail__c = ImportantNotes.Mail__c,
                                                            INReflectionTime__c = Datetime.now()
                                                )
                );
                // 保護者OBJデータ更新
                if (AccountTMP.size() > 0) {
                    try{
System.debug('update AccountTMP　'+AccountTMP);
                        update AccountTMP;
                    }catch(DmlException e){
                        System.debug('ImportantNotes__c 保護者OBJの更新失敗');
                        Integer errNum = e.getNumDml();
                        for(Integer i = 0; i < errNum; i++){
                            AccountTMP.get(e.getDmlIndex(i)).addError('保護者データ更新時にエラーが発生しました'+e.getDmlMessage(i));
                        }
                    }
                }
                
            }

        }

        // 処理完了メッセージ
        return '反映処理が完了しました！';
    }
}