force-app/main/default/objects/Account/fields/RelationshipWithChildren1__c.field-meta.xml
<CustomField>
    <fullName>RelationshipWithChildren1__c</fullName>
    <label>保護者１：子との関係</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RelationshipWithChildren</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EntryDate__c.field-meta.xml
<CustomField>
    <fullName>EntryDate__c</fullName>
    <label>入園年月日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/kana__c.field-meta.xml
<CustomField>
    <fullName>kana__c</fullName>
    <label>ふりがな</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RelationshipWithChildren1__c.field-meta.xml
<CustomField>
    <fullName>RelationshipWithChildren1__c</fullName>
    <formula>TEXT( Account.RelationshipWithChildren1__c )</formula>
    <label>保護者１：関係</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <formula>TEXT(Account.School__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>幼稚園</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>性別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>男子</fullName>
            </value>
            <value>
                <fullName>女子</fullName>
            </value>
            <value>
                <fullName>男</fullName>
            </value>
            <value>
                <fullName>女</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/ImportantNotes__c.object-meta.xml
<CustomObject>
    <label>要録情報</label>
    <nameField>
        <displayFormat>IN{YYYY}/{MM}-{000}</displayFormat>
        <label>要録情報名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ImportantNotes__c/fields/EntryDate__c.field-meta.xml
<CustomField>
    <fullName>EntryDate__c</fullName>
    <formula>Contact__r.EntryDate__c</formula>
    <label>入園年月日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/RelationshipWithChildren1__c.field-meta.xml
<CustomField>
    <fullName>RelationshipWithChildren1__c</fullName>
    <formula>Contact__r.RelationshipWithChildren1__c</formula>
    <label>保護者１：関係</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <formula>TEXT(Contact__r.Sex__c)</formula>
    <label>性別</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/KindergartenDiary__c.object-meta.xml
<CustomObject>
    <label>園児日誌</label>
    <nameField>
        <displayFormat>日誌{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>園児日誌</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/KindergartenDiary__c/fields/ImportantNotes__c.field-meta.xml
<CustomField>
    <fullName>ImportantNotes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>要録情報</label>
    <referenceTo>ImportantNotes__c</referenceTo>
    <relationshipLabel>園児日誌</relationshipLabel>
    <relationshipName>ChildDailyR_ImportantNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <label>幼稚園</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SchoolSelection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <label>職員名簿</label>
    <nameField>
        <label>職員名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <label>幼稚園</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>北広島わかば</fullName>
            </value>
            <value>
                <fullName>平岸</fullName>
            </value>
            <value>
                <fullName>カルチュア</fullName>
            </value>
            <value>
                <fullName>ケーアンドケー</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/fields/WorkDivision__c.field-meta.xml
<CustomField>
    <fullName>WorkDivision__c</fullName>
    <label>勤務区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>正職保育教諭</fullName>
            </value>
            <value>
                <fullName>正職員</fullName>
            </value>
            <value>
                <fullName>時給保育教諭</fullName>
            </value>
            <value>
                <fullName>時給職員</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestImportantNotesController.cls
@isTest
// This class is bound to API version 45.0 by Version Settings
public with sharing class TestImportantNotesController {

    @isTest static void test_ImportantNotes() {
        
        // 職員名簿のテストデータを作成する
        Staff__c staff1 = new Staff__c(
            Name='テスト職員A',
            WorkDivision__c ='正職員',
            School__c='北広島わかば'
        );
        insert staff1;
        
        // 保護者のテストデータを作成する
        Account act1 = new Account(
                    Name='テスト保護者',
                    RelationshipWithChildren1__c='父',
                    School__c='北広島わかば'
        );
        insert act1;
        Account ACTID = act1;

        // 園児のテストデータを作成する
        Date BTD = Date.newInstance(2014, 1, 29);
        Date ETD = Date.newInstance(2017, 4, 3);
        Contact cnt1 = new Contact(
                    FirstName='園児男子',
                    LastName='テスト',
                    Sex__c='男子',
                    kana__c='てすと えんじだんし',
                    Birthdate=BTD,
                    EntryDate__c=ETD,
                    AccountId=ACTID.Id
        );
        insert cnt1;
        Contact CNTID = cnt1;

        // テスト開始        
        Test.startTest();

        List<Staff__c> Staff = ImportantNotesController.findStaff();

        List<KindergartenDiary__c> KindergartenDiary1 = ImportantNotesController.findKindergartenDiary_OrList('2019-05-01 00:00:00','2019-05-31 00:00:00',CNTID.Id);

        List<ImportantNotes__c> ImportantNotes1 = ImportantNotesController.findImportantNotes2('ゆり','2019-05-16 00:00:00','class');
        List<ImportantNotes__c> ImportantNotes2 = ImportantNotesController.findImportantNotes2('ゆり','2019-02-15 00:00:00','class');
        List<ImportantNotes__c> ImportantNotes3 = ImportantNotesController.findImportantNotes2('通園コース1','2019-05-19 00:00:00','bus');
        List<ImportantNotes__c> ImportantNotes4 = ImportantNotesController.findImportantNotes2('通園コース1','2019-05-19 00:00:00','buss');

        List<KindergartenDiary__c> KindergartenDiary2 = ImportantNotesController.findKindergartenDiary('2019-05-01 00:00:00');
        Test.stopTest();

    }    

}