force-app/main/default/objects/Account/fields/RelationshipWithChildren1__c.field-meta.xml
<CustomField>
    <fullName>RelationshipWithChildren1__c</fullName>
    <label>保護者１：子との関係</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RelationshipWithChildren</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>学級</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>★★ぐみ</fullName>
            </value>
            <value>
                <fullName>●●ぐみ</fullName>
            </value>
            <value>
                <fullName>▼▼ぐみ</fullName>
            </value>
            <value>
                <fullName>ゆり</fullName>
            </value>
            <value>
                <fullName>きく</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EntryDate__c.field-meta.xml
<CustomField>
    <fullName>EntryDate__c</fullName>
    <label>入園年月日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/kana__c.field-meta.xml
<CustomField>
    <fullName>kana__c</fullName>
    <label>ふりがな</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>園児番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <label>通園コース</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>犬１</fullName>
            </value>
            <value>
                <fullName>犬２</fullName>
            </value>
            <value>
                <fullName>ネコ１</fullName>
            </value>
            <value>
                <fullName>ネコ２</fullName>
            </value>
            <value>
                <fullName>ビーバー</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/RelationshipWithChildren1__c.field-meta.xml
<CustomField>
    <fullName>RelationshipWithChildren1__c</fullName>
    <formula>TEXT( Account.RelationshipWithChildren1__c )</formula>
    <label>保護者１：関係</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <formula>TEXT(Account.School__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>幼稚園</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>性別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>男子</fullName>
            </value>
            <value>
                <fullName>女子</fullName>
            </value>
            <value>
                <fullName>男</fullName>
            </value>
            <value>
                <fullName>女</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/ImportantNotes__c.object-meta.xml
<CustomObject>
    <label>要録情報</label>
    <nameField>
        <displayFormat>IN{YYYY}/{MM}-{000}</displayFormat>
        <label>要録情報名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ImportantNotes__c/fields/BusDisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>BusDisplayOrder__c</fullName>
    <label>バス表示順</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>学級</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>みつば</fullName>
            </value>
            <value>
                <fullName>ふたば</fullName>
            </value>
            <value>
                <fullName>つぼみ</fullName>
            </value>
            <value>
                <fullName>あさがお</fullName>
            </value>
            <value>
                <fullName>すみれ</fullName>
            </value>
            <value>
                <fullName>たんぽぽ</fullName>
            </value>
            <value>
                <fullName>ばら</fullName>
            </value>
            <value>
                <fullName>さくら</fullName>
            </value>
            <value>
                <fullName>きく</fullName>
            </value>
            <value>
                <fullName>ゆり</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>園児</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>要録情報</relationshipLabel>
    <relationshipName>ImportantNotes_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/EntryDate__c.field-meta.xml
<CustomField>
    <fullName>EntryDate__c</fullName>
    <formula>Contact__r.EntryDate__c</formula>
    <label>入園年月日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>FiscalYear__c</fullName>
    <label>年度</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>園児番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <formula>TEXT(Contact__r.PassageRoute__c)</formula>
    <label>通園コース</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/RelationshipWithChildren1__c.field-meta.xml
<CustomField>
    <fullName>RelationshipWithChildren1__c</fullName>
    <formula>Contact__r.RelationshipWithChildren1__c</formula>
    <label>保護者１：関係</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <formula>TEXT(Contact__r.Sex__c)</formula>
    <label>性別</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/KindergartenDiary__c.object-meta.xml
<CustomObject>
    <label>園児日誌</label>
    <nameField>
        <displayFormat>日誌{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>園児日誌</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/KindergartenDiary__c/fields/AttendanceSchedule__c.field-meta.xml
<CustomField>
    <fullName>AttendanceSchedule__c</fullName>
    <label>出欠席予定</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>出席予定</fullName>
            </value>
            <value>
                <fullName>欠席予定</fullName>
            </value>
            <value>
                <fullName>出席</fullName>
            </value>
            <value>
                <fullName>欠席</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>学級</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClassSelection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>園児名</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>ChildDailyR_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>日付</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/ImportantNotes__c.field-meta.xml
<CustomField>
    <fullName>ImportantNotes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>要録情報</label>
    <referenceTo>ImportantNotes__c</referenceTo>
    <relationshipLabel>園児日誌</relationshipLabel>
    <relationshipName>ChildDailyR_ImportantNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/Outside__c.field-meta.xml
<CustomField>
    <fullName>Outside__c</fullName>
    <label>時間外保育</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>14:30</fullName>
            </value>
            <value>
                <fullName>16:00</fullName>
            </value>
            <value>
                <fullName>17:00</fullName>
            </value>
            <value>
                <fullName>18:00</fullName>
            </value>
            <value>
                <fullName>18:30</fullName>
            </value>
            <value>
                <fullName>19:00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/OutsideFast__c.field-meta.xml
<CustomField>
    <fullName>OutsideFast__c</fullName>
    <label>時間外保育：早朝</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7:00</fullName>
            </value>
            <value>
                <fullName>7:30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <label>通園コース</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusSelection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <label>幼稚園</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SchoolSelection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/StaffId__c.field-meta.xml
<CustomField>
    <fullName>StaffId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>更新者</label>
    <referenceTo>Staff__c</referenceTo>
    <relationshipLabel>最後に更新した園児日誌</relationshipLabel>
    <relationshipName>LastUpdatedKindergartenDiaryes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <label>職員名簿</label>
    <nameField>
        <label>職員名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <label>幼稚園</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>北広島わかば</fullName>
            </value>
            <value>
                <fullName>平岸</fullName>
            </value>
            <value>
                <fullName>カルチュア</fullName>
            </value>
            <value>
                <fullName>ケーアンドケー</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/fields/WorkDivision__c.field-meta.xml
<CustomField>
    <fullName>WorkDivision__c</fullName>
    <label>勤務区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>正職保育教諭</fullName>
            </value>
            <value>
                <fullName>正職員</fullName>
            </value>
            <value>
                <fullName>時給保育教諭</fullName>
            </value>
            <value>
                <fullName>時給職員</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestImportantNotesV2Controller.cls
@isTest
// This class is bound to API version 45.0 by Version Settings
public with sharing class TestImportantNotesV2Controller {

    @isTest static void test_ImportantNotes() {
        
        // 職員名簿のテストデータを作成する
        Staff__c staff1 = new Staff__c(
            Name='テスト職員A',
            WorkDivision__c ='正職員',
            School__c='北広島わかば'
        );
        insert staff1;
        Staff__c STFID = staff1;
        
        // 保護者のテストデータを作成する
        Account act1 = new Account(
                    Name='テスト保護者',
                    RelationshipWithChildren1__c='父',
                    School__c='北広島わかば'
        );
        insert act1;
        Account ACTID = act1;

        // 園児のテストデータを作成する
        Date BTD = Date.newInstance(2014, 1, 29);
        Date ETD = Date.newInstance(2017, 4, 3);
        Contact cnt1 = new Contact(
                    FirstName='園児男子',
                    LastName='テスト',
                    Sex__c='男子',
                    kana__c='てすと えんじだんし',
                    Birthdate=BTD,
                    EntryDate__c=ETD,
                    AccountId=ACTID.Id
        );
        insert cnt1;
        Contact CNTID = cnt1;

        // 園児日誌のテストデータを作成する
        Date TDY = date.today();
        KindergartenDiary__c kgd1 = new KindergartenDiary__c(
					Contact__c = CNTID.Id,
            		Date__c = TDY,
            		AttendanceSchedule__c = '欠席',
					StaffId__c = STFID.Id
        );
        insert kgd1;
        KindergartenDiary__c KGDID = kgd1;

        // 要録情報のテストデータを作成する
        ImportantNotes__c itn1 = new ImportantNotes__c(
                    FiscalYear__c='2019',
                    Contact__c=CNTID.Id,
            		Class__c='ゆり',
            		PassageRoute__c = '犬１',
            		Number__c = '101',
            		BusDisplayOrder__c = '101',
                    School__c='北広島わかば'
        );
        insert itn1;
        ImportantNotes__c ITNID = itn1;


        // insertList設定
        List<KindergartenDiary__c> insertList = new List<KindergartenDiary__c>();
        insertList.add(new KindergartenDiary__c(
								Date__c = TDY,
								Contact__c = CNTID.Id,
								Outside__c = '16:00',
								OutsideFast__c  = '7:00',
								StaffId__c = STFID.Id)
        );

        // updateList設定
        List<KindergartenDiary__c> updateList = new List<KindergartenDiary__c>();
        updateList.add(new KindergartenDiary__c(
								Id = KGDID.Id,
								Date__c = TDY,
								Contact__c = CNTID.Id,
								Outside__c = '16:00',
								OutsideFast__c  = '7:00',
								StaffId__c = STFID.Id)
        );

		Map<Id, Contact> contactMap = new Map<Id, Contact>([SELECT Id, Name FROM Contact]);
		List<Id> ContactList = new List<Id>(contactMap.keySet());

        // テスト開始        
        Test.startTest();

        List<Staff__c> Staff = ImportantNotesV2Controller.findStaff('北広島わかば');
        List<Staff__c> Staff2 = ImportantNotesV2Controller.findStaff('');

//        List<KindergartenDiary__c> KindergartenDiary1 = ImportantNotesV2Controller.findKindergartenDiary_OrList('2019-05-01 00:00:00','2019-05-31 00:00:00',CNTID.Id);

        List<ImportantNotes__c> ImportantNotes1 = ImportantNotesV2Controller.findImportantNotes('2019','北広島わかば');
        List<ImportantNotes__c> ImportantNotes2 = ImportantNotesV2Controller.findImportantNotes('2019','');
//        List<ImportantNotes__c> ImportantNotes3 = ImportantNotesV2Controller.findImportantNotes('2019','北広島わかば');
//        List<ImportantNotes__c> ImportantNotes4 = ImportantNotesV2Controller.findImportantNotes('2019','北広島わかば');

        List<KindergartenDiary__c> KindergartenDiary2 = ImportantNotesV2Controller.findKindergartenDiary('2019-08-29', ContactList);

//        String result = ImportantNotesV2Controller.upsertKindergartenDiary( insertList, updateList );

        Test.stopTest();
    }    

}