force-app/main/default/objects/Account/fields/RelationshipWithChildren1__c.field-meta.xml
<CustomField>
    <fullName>RelationshipWithChildren1__c</fullName>
    <label>保護者１：子との関係</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RelationshipWithChildren</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChildcareFee__c/ChildcareFee__c.object-meta.xml
<CustomObject>
    <label>保育料</label>
    <nameField>
        <displayFormat>CF{YYYY}{MM}-{000}</displayFormat>
        <label>保育料名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChildcareFee__c/fields/Belongs__c.field-meta.xml
<CustomField>
    <fullName>Belongs__c</fullName>
    <formula>TEXT(ImportantNotes__r.Belongs__c)</formula>
    <label>所属</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChildcareFee__c/fields/ChildcareFee__c.field-meta.xml
<CustomField>
    <fullName>ChildcareFee__c</fullName>
    <defaultValue>0</defaultValue>
    <label>保育料</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ChildcareFee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>園児</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>保育料</relationshipLabel>
    <relationshipName>ChildcareFee_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChildcareFee__c/fields/ImportantNotes__c.field-meta.xml
<CustomField>
    <fullName>ImportantNotes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>要録情報</label>
    <referenceTo>ImportantNotes__c</referenceTo>
    <relationshipLabel>保育料</relationshipLabel>
    <relationshipName>ChildcareFees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChildcareFee__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <formula>ImportantNotes__r.Number__c</formula>
    <label>園児番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChildcareFee__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>年</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
                <default>true</default>
                <label>2019</label>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Belongs__c.field-meta.xml
<CustomField>
    <fullName>Belongs__c</fullName>
    <label>所属</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>幼稚園部</fullName>
            </value>
            <value>
                <fullName>保育園部の標準時間</fullName>
            </value>
            <value>
                <fullName>保育園部の短時間</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>学級</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>★★ぐみ</fullName>
            </value>
            <value>
                <fullName>●●ぐみ</fullName>
            </value>
            <value>
                <fullName>▼▼ぐみ</fullName>
            </value>
            <value>
                <fullName>ゆり</fullName>
            </value>
            <value>
                <fullName>きく</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/EntryDate__c.field-meta.xml
<CustomField>
    <fullName>EntryDate__c</fullName>
    <label>入園年月日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/kana__c.field-meta.xml
<CustomField>
    <fullName>kana__c</fullName>
    <label>ふりがな</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>園児番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <label>通園コース</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>犬１</fullName>
            </value>
            <value>
                <fullName>犬２</fullName>
            </value>
            <value>
                <fullName>ネコ１</fullName>
            </value>
            <value>
                <fullName>ネコ２</fullName>
            </value>
            <value>
                <fullName>ビーバー</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/RelationshipWithChildren1__c.field-meta.xml
<CustomField>
    <fullName>RelationshipWithChildren1__c</fullName>
    <formula>TEXT( Account.RelationshipWithChildren1__c )</formula>
    <label>保護者１：関係</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <formula>TEXT(Account.School__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>幼稚園</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>性別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>男子</fullName>
            </value>
            <value>
                <fullName>女子</fullName>
            </value>
            <value>
                <fullName>男</fullName>
            </value>
            <value>
                <fullName>女</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/ImportantNotes__c.object-meta.xml
<CustomObject>
    <label>要録情報</label>
    <nameField>
        <displayFormat>IN{YYYY}/{MM}-{000}</displayFormat>
        <label>要録情報名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ImportantNotes__c/fields/BusDisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>BusDisplayOrder__c</fullName>
    <label>バス表示順</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>学級</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>みつば</fullName>
            </value>
            <value>
                <fullName>ふたば</fullName>
            </value>
            <value>
                <fullName>つぼみ</fullName>
            </value>
            <value>
                <fullName>あさがお</fullName>
            </value>
            <value>
                <fullName>すみれ</fullName>
            </value>
            <value>
                <fullName>たんぽぽ</fullName>
            </value>
            <value>
                <fullName>ばら</fullName>
            </value>
            <value>
                <fullName>さくら</fullName>
            </value>
            <value>
                <fullName>きく</fullName>
            </value>
            <value>
                <fullName>ゆり</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>園児</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>要録情報</relationshipLabel>
    <relationshipName>ImportantNotes_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/EntryDate__c.field-meta.xml
<CustomField>
    <fullName>EntryDate__c</fullName>
    <formula>Contact__r.EntryDate__c</formula>
    <label>入園年月日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>FiscalYear__c</fullName>
    <label>年度</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>園児番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <formula>TEXT(Contact__r.PassageRoute__c)</formula>
    <label>通園コース</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/RelationshipWithChildren1__c.field-meta.xml
<CustomField>
    <fullName>RelationshipWithChildren1__c</fullName>
    <formula>Contact__r.RelationshipWithChildren1__c</formula>
    <label>保護者１：関係</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <formula>TEXT(Contact__r.Sex__c)</formula>
    <label>性別</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/KindergartenDiary__c.object-meta.xml
<CustomObject>
    <label>園児日誌</label>
    <nameField>
        <displayFormat>日誌{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>園児日誌</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/KindergartenDiary__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>学級</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClassSelection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>園児名</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>ChildDailyR_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>日付</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/ImportantNotes__c.field-meta.xml
<CustomField>
    <fullName>ImportantNotes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>要録情報</label>
    <referenceTo>ImportantNotes__c</referenceTo>
    <relationshipLabel>園児日誌</relationshipLabel>
    <relationshipName>ChildDailyR_ImportantNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <label>通園コース</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusSelection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <label>幼稚園</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SchoolSelection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <label>職員名簿</label>
    <nameField>
        <label>職員名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <label>幼稚園</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>北広島わかば</fullName>
            </value>
            <value>
                <fullName>平岸</fullName>
            </value>
            <value>
                <fullName>カルチュア</fullName>
            </value>
            <value>
                <fullName>ケーアンドケー</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff__c/fields/WorkDivision__c.field-meta.xml
<CustomField>
    <fullName>WorkDivision__c</fullName>
    <label>勤務区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>正職保育教諭</fullName>
            </value>
            <value>
                <fullName>正職員</fullName>
            </value>
            <value>
                <fullName>時給保育教諭</fullName>
            </value>
            <value>
                <fullName>時給職員</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAttendanceCountController.cls
@isTest
public class TestAttendanceCountController {
    
    @isTest static void test_AttendanceCount() {
        
        // 職員名簿のテストデータを作成する
        Staff__c staff1 = new Staff__c(
            Name='テスト職員A',
            WorkDivision__c ='正職員',
            School__c='北広島わかば'
        );
        insert staff1;
        Staff__c STFID = staff1;
        
        // 保護者のテストデータを作成する
        Account act1 = new Account(
                    Name='テスト保護者',
                    RelationshipWithChildren1__c='父',
                    School__c='北広島わかば'
        );
        insert act1;
        Account ACTID = act1;

        // 園児のテストデータを作成する
        Date BTD = Date.newInstance(2014, 1, 29);
        Date ETD = Date.newInstance(2017, 4, 3);
        Contact cnt1 = new Contact(
                    FirstName='園児男子1',
                    LastName='テスト1',
                    Sex__c='男子',
                    kana__c='てすと えんじだんし',
                    Birthdate=BTD,
                    EntryDate__c=ETD,
                    AccountId=ACTID.Id
        );
        insert cnt1;
        Contact CNTID1 = cnt1;

        Contact cnt2 = new Contact(
                    FirstName='園児男子2',
                    LastName='テスト2',
                    Sex__c='男子',
                    kana__c='てすと えんじだんし',
                    Birthdate=BTD,
                    EntryDate__c=ETD,
                    AccountId=ACTID.Id
        );
        insert cnt2;
        Contact CNTID2 = cnt2;

        Contact cnt3 = new Contact(
                    FirstName='園児男子3',
                    LastName='テスト3',
                    Sex__c='男子',
                    kana__c='てすと えんじだんし',
                    Birthdate=BTD,
                    EntryDate__c=ETD,
                    AccountId=ACTID.Id
        );
        insert cnt3;
        Contact CNTID3 = cnt3;


        Date TDY = date.today();
        String YEAR = String.ValueOf(TDY.year());
        String MONTH = String.ValueOf(TDY.month());

        // 要録情報のテストデータを作成する
        ImportantNotes__c itn1 = new ImportantNotes__c(
                    FiscalYear__c= YEAR,
                    Contact__c=CNTID1.Id,
                    Belongs__c = '幼稚園部',
                    Class__c='ゆり',
                    PassageRoute__c = '犬１',
                    Number__c = '101',
                    BusDisplayOrder__c = '101',
                    School__c='北広島わかば'
        );
        insert itn1;
        ImportantNotes__c ITNID1 = itn1;

        ImportantNotes__c itn2 = new ImportantNotes__c(
                    FiscalYear__c= YEAR,
                    Contact__c=CNTID2.Id,
                    Belongs__c = '保育園部の標準時間',
                    Class__c='ゆり',
                    PassageRoute__c = '犬１',
                    Number__c = '102',
                    BusDisplayOrder__c = '102',
                    School__c='北広島わかば'
        );
        insert itn2;
        ImportantNotes__c ITNID2 = itn2;

        ImportantNotes__c itn3 = new ImportantNotes__c(
                    FiscalYear__c= YEAR,
                    Contact__c=CNTID3.Id,
                    Belongs__c = '保育園部の短時間',
                    Class__c='ゆり',
                    PassageRoute__c = '犬１',
                    Number__c = '10３',
                    BusDisplayOrder__c = '10３',
                    School__c='北広島わかば'
        );
        insert itn3;
        ImportantNotes__c ITNID3 = itn3;


        // 保育料のテストデータを作成する
        ChildcareFee__c ccf1 = new ChildcareFee__c(
                    Year__c = YEAR,
                    Month__c = MONTH,
                    Contact__c=CNTID1.Id
        );
        insert ccf1;
        ChildcareFee__c CCFID1 = ccf1;

        ChildcareFee__c ccf2 = new ChildcareFee__c(
                    Year__c = YEAR,
                    Month__c = MONTH,
                    Contact__c=CNTID2.Id
        );
        insert ccf2;
        ChildcareFee__c CCFID2 = ccf2;

        ChildcareFee__c ccf3 = new ChildcareFee__c(
                    Year__c = YEAR,
                    Month__c = MONTH,
                    Contact__c=CNTID3.Id
        );
        insert ccf3;
        ChildcareFee__c CCFID3 = ccf3;



        // 園児日誌のテストデータを作成する
        KindergartenDiary__c kgd1 = new KindergartenDiary__c(
                    Contact__c = CNTID1.Id,
                    Date__c = TDY,
                    AttendanceSchedule__c = '欠席',
                    Belongs__c = '幼稚園部',
                    ImportantNotes__c = ITNID1.Id,
                    AttendanceStopReason__c = 'インフルエンザ',
                    Lateness__c = False,
                    LeaveEarly__c = False,
                    StaffId__c = STFID.Id
        );
        insert kgd1;
        KindergartenDiary__c KGDID1 = kgd1;

        KindergartenDiary__c kgd2 = new KindergartenDiary__c(
                    Contact__c = CNTID1.Id,
                    Date__c = TDY+1,
                    AttendanceSchedule__c = '出席',
                    Belongs__c = '幼稚園部',
                    ImportantNotes__c = ITNID1.Id,
                    AttendanceStopReason__c = '',
                    Lateness__c = True,
                    LeaveEarly__c = True,
                    StaffId__c = STFID.Id
        );
        insert kgd2;
        KindergartenDiary__c KGDID2 = kgd2;

        KindergartenDiary__c kgd3 = new KindergartenDiary__c(
                    Contact__c = CNTID2.Id,
                    Date__c = TDY+2,
                    AttendanceSchedule__c = '出席',
                    Belongs__c = '保育園部の標準時間',
                    ImportantNotes__c = ITNID2.Id,
                    AttendanceStopReason__c = '',
                    Lateness__c = True,
                    LeaveEarly__c = True,
                    StaffId__c = STFID.Id
        );
        insert kgd3;
        KindergartenDiary__c KGDID3 = kgd3;

        KindergartenDiary__c kgd4 = new KindergartenDiary__c(
                    Contact__c = CNTID3.Id,
                    Date__c = TDY+3,
                    AttendanceSchedule__c = '出席',
                    Belongs__c = '保育園部の短時間',
                    ImportantNotes__c = ITNID3.Id,
                    AttendanceStopReason__c = '',
                    Lateness__c = True,
                    LeaveEarly__c = True,
                    StaffId__c = STFID.Id
        );
        insert kgd4;
        KindergartenDiary__c KGDID4 = kgd4;

        KindergartenDiary__c kgd5 = new KindergartenDiary__c(
                    Contact__c = CNTID1.Id,
                    Date__c = TDY+4,
                    AttendanceSchedule__c = '出席',
                    Belongs__c = NULL,
                    ImportantNotes__c = ITNID1.Id,
                    AttendanceStopReason__c = '',
                    Lateness__c = True,
                    LeaveEarly__c = True,
                    StaffId__c = STFID.Id
        );
        insert kgd5;
        KindergartenDiary__c KGDID5 = kgd5;

        KindergartenDiary__c kgd6 = new KindergartenDiary__c(
                    Contact__c = CNTID2.Id,
                    Date__c = TDY+5,
                    Belongs__c = NULL,
                    ImportantNotes__c = ITNID2.Id,
                    AttendanceSchedule__c = '出席',
                    AttendanceStopReason__c = '',
                    Lateness__c = True,
                    LeaveEarly__c = True,
                    StaffId__c = STFID.Id
        );
        insert kgd6;
        KindergartenDiary__c KGDID6 = kgd6;

        KindergartenDiary__c kgd7 = new KindergartenDiary__c(
                    Contact__c = CNTID3.Id,
                    Date__c = TDY+6,
                    Belongs__c = NULL,
                    ImportantNotes__c = ITNID3.Id,
                    AttendanceSchedule__c = '出席',
                    AttendanceStopReason__c = '',
                    Lateness__c = True,
                    LeaveEarly__c = True,
                    StaffId__c = STFID.Id
        );
        insert kgd7;
        KindergartenDiary__c KGDID7 = kgd7;

        KindergartenDiary__c kgd8 = new KindergartenDiary__c(
                    Contact__c = CNTID1.Id,
                    Date__c = TDY+7,
                    Belongs__c = NULL,
                    ImportantNotes__c = ITNID1.Id,
                    AttendanceSchedule__c = '出席',
                    AttendanceStopReason__c = '',
                    Lateness__c = True,
                    LeaveEarly__c = True,
                    StaffId__c = STFID.Id
        );
        insert kgd8;
        KindergartenDiary__c kgd9 = new KindergartenDiary__c(
                    Id = kgd8.Id,
                    Belongs__c = NULL
        );
        update kgd9;

        KindergartenDiary__c kgd10 = new KindergartenDiary__c(
                    Contact__c = CNTID2.Id,
                    Date__c = TDY+8,
                    Belongs__c = NULL,
                    ImportantNotes__c = ITNID3.Id,
                    AttendanceSchedule__c = '出席',
                    AttendanceStopReason__c = '',
                    Lateness__c = True,
                    LeaveEarly__c = True,
                    StaffId__c = STFID.Id
        );
        insert kgd10;
        KindergartenDiary__c kgd11 = new KindergartenDiary__c(
                    Id = kgd10.Id,
                    Belongs__c = NULL
        );
        update kgd11;


        // テスト開始        
        Test.startTest();

        String result = '';
        result = AttendanceCountController.AttendanceCounting( ITNID1.Id );
        result = AttendanceCountController.AttendanceCounting( ITNID2.Id );
        result = AttendanceCountController.AttendanceCounting( ITNID3.Id );

        Test.stopTest();



    }
}