force-app/main/default/objects/Contact/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>学級</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>★★ぐみ</fullName>
            </value>
            <value>
                <fullName>●●ぐみ</fullName>
            </value>
            <value>
                <fullName>▼▼ぐみ</fullName>
            </value>
            <value>
                <fullName>ゆり</fullName>
            </value>
            <value>
                <fullName>きく</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/kana__c.field-meta.xml
<CustomField>
    <fullName>kana__c</fullName>
    <label>ふりがな</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <label>通園コース</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>犬１</fullName>
            </value>
            <value>
                <fullName>犬２</fullName>
            </value>
            <value>
                <fullName>ネコ１</fullName>
            </value>
            <value>
                <fullName>ネコ２</fullName>
            </value>
            <value>
                <fullName>ビーバー</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/ImportantNotes__c.object-meta.xml
<CustomObject>
    <label>要録情報</label>
    <nameField>
        <displayFormat>IN{YYYY}/{MM}-{000}</displayFormat>
        <label>要録情報名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ImportantNotes__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>学級</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>みつば</fullName>
            </value>
            <value>
                <fullName>ふたば</fullName>
            </value>
            <value>
                <fullName>つぼみ</fullName>
            </value>
            <value>
                <fullName>あさがお</fullName>
            </value>
            <value>
                <fullName>すみれ</fullName>
            </value>
            <value>
                <fullName>たんぽぽ</fullName>
            </value>
            <value>
                <fullName>ばら</fullName>
            </value>
            <value>
                <fullName>さくら</fullName>
            </value>
            <value>
                <fullName>きく</fullName>
            </value>
            <value>
                <fullName>ゆり</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>園児</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>要録情報</relationshipLabel>
    <relationshipName>ImportantNotes_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/DisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>DisplayOrder__c</fullName>
    <formula>IF( ISBLANK(Contact__r.EntryDate__c),
&quot;99999999&quot;,
TEXT( YEAR(Contact__r.EntryDate__c) ) + LPAD(TEXT(MONTH(Contact__r.EntryDate__c)), 2 , &#39;0&#39;)  + LPAD(TEXT(DAY(Contact__r.EntryDate__c)), 2 , &#39;0&#39;)
)

+

CASE( Contact__r.Sex__c ,
   &quot;男子&quot;, &quot;0&quot;,
   &quot;女子&quot;, &quot;1&quot;,
   &quot;9&quot;
)

+

IF( ISBLANK(Contact__r.Birthdate ),
&quot;99999999&quot;,
TEXT( YEAR(Contact__r.Birthdate) ) + LPAD(TEXT(MONTH(Contact__r.Birthdate)), 2 , &#39;0&#39;)  + LPAD(TEXT(DAY(Contact__r.Birthdate)), 2 , &#39;0&#39;)
)</formula>
    <label>表示順</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/DropOffText__c.field-meta.xml
<CustomField>
    <fullName>DropOffText__c</fullName>
    <formula>LEFT(TEXT(DropOff__c),5)</formula>
    <label>[表示]バス送り時間</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>FiscalYear__c</fullName>
    <label>年度</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <formula>TEXT(Contact__r.PassageRoute__c)</formula>
    <label>通園コース</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/PickUpTime__c.field-meta.xml
<CustomField>
    <fullName>PickUpTime__c</fullName>
    <label>バス迎え時間</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/PickUpTimeText__c.field-meta.xml
<CustomField>
    <fullName>PickUpTimeText__c</fullName>
    <formula>LEFT(TEXT(PickUpTime__c),5)</formula>
    <label>[表示]バス迎え時間</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>備考</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/KindergartenDiary__c.object-meta.xml
<CustomObject>
    <label>園児日誌</label>
    <nameField>
        <displayFormat>日誌{YYYY}{MM}{DD}-{000}</displayFormat>
        <label>園児日誌</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/KindergartenDiary__c/fields/AbsenceReason__c.field-meta.xml
<CustomField>
    <fullName>AbsenceReason__c</fullName>
    <label>欠席理由</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>病気のため</fullName>
            </value>
            <value>
                <fullName>保護者がお休みのため</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/AbsentSchedule__c.field-meta.xml
<CustomField>
    <fullName>AbsentSchedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>欠席予定</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/AttendanceSchedule__c.field-meta.xml
<CustomField>
    <fullName>AttendanceSchedule__c</fullName>
    <label>出欠席予定</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>出席予定</fullName>
            </value>
            <value>
                <fullName>欠席予定</fullName>
            </value>
            <value>
                <fullName>出席</fullName>
            </value>
            <value>
                <fullName>欠席</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/AttendanceTime__c.field-meta.xml
<CustomField>
    <fullName>AttendanceTime__c</fullName>
    <label>出席時間</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/AttendingSchool__c.field-meta.xml
<CustomField>
    <fullName>AttendingSchool__c</fullName>
    <defaultValue>false</defaultValue>
    <label>登園</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/attendingSchoolTime__c.field-meta.xml
<CustomField>
    <fullName>attendingSchoolTime__c</fullName>
    <label>登園時間</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/BusBackNotUse__c.field-meta.xml
<CustomField>
    <fullName>BusBackNotUse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>バス帰り利用なし</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/BusGoingNotUse__c.field-meta.xml
<CustomField>
    <fullName>BusGoingNotUse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>バス行き利用なし</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>学級</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClassSelection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>園児名</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>ChildDailyR_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>日付</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/GoingBack__c.field-meta.xml
<CustomField>
    <fullName>GoingBack__c</fullName>
    <defaultValue>false</defaultValue>
    <label>降園</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/GoingBackTime__c.field-meta.xml
<CustomField>
    <fullName>GoingBackTime__c</fullName>
    <label>降園時間</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/ImportantNotes__c.field-meta.xml
<CustomField>
    <fullName>ImportantNotes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>要録情報</label>
    <referenceTo>ImportantNotes__c</referenceTo>
    <relationshipLabel>園児日誌</relationshipLabel>
    <relationshipName>ChildDailyR_ImportantNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/Outside__c.field-meta.xml
<CustomField>
    <fullName>Outside__c</fullName>
    <label>時間外保育</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>14:30</fullName>
            </value>
            <value>
                <fullName>16:00</fullName>
            </value>
            <value>
                <fullName>17:00</fullName>
            </value>
            <value>
                <fullName>18:00</fullName>
            </value>
            <value>
                <fullName>18:30</fullName>
            </value>
            <value>
                <fullName>19:00</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/OutsideFast__c.field-meta.xml
<CustomField>
    <fullName>OutsideFast__c</fullName>
    <label>時間外保育：早朝</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>7:00</fullName>
            </value>
            <value>
                <fullName>7:30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/PassageRoute__c.field-meta.xml
<CustomField>
    <fullName>PassageRoute__c</fullName>
    <label>通園コース</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusSelection</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/KindergartenDiary__c/fields/PickUpTime__c.field-meta.xml
<CustomField>
    <fullName>PickUpTime__c</fullName>
    <label>お迎え予定</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <label>職員名簿</label>
    <nameField>
        <label>職員名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff__c/fields/ListDisplayCheck__c.field-meta.xml
<CustomField>
    <fullName>ListDisplayCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>職員リストに表示</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ImportantNotesController.cls
public with sharing class ImportantNotesController {
    /* 使わない
    @AuraEnabled(cacheable=true)
    public static List<ImportantNotes__c> getImportantNotesList() {
        return [SELECT Id, Name,Class__c FROM ImportantNotes__c];
    }

    @AuraEnabled(cacheable=true)
    public static List<ImportantNotes__c> findImportantNotes(String searchKey) {
        if (String.isBlank(searchKey)) {
            return new List<ImportantNotes__c>();
        }
        String key = searchKey;
        return [SELECT Id, Name , Contact__r.kana__c , Class__c,Remarks__c FROM ImportantNotes__c WHERE Class__c =: searchKey];
    }
    */

    /* ------------------------------------------------------------------------
        共通：職員一覧を呼び出し　overtimeReservation / staffAttendanceMenu03
    ------------------------------------------------------------------------ */
    @AuraEnabled(cacheable=true)
    public static List<Staff__c> findStaff() {
        return [SELECT Id,Name FROM Staff__c WHERE ListDisplayCheck__c = true  ];
    }
    


    /* ------------------------------------------------
        overtimeReservation:園児日誌一覧を取得
    ------------------------------------------------ */
    @AuraEnabled
    public static List<KindergartenDiary__c> findKindergartenDiary_OrList(String StartDate,String EndDate,String EnjiID) {
        Date StartDateS = Date.valueOf(StartDate);
        Date EndDateS = Date.valueOf(EndDate);

        system.debug('StartDateS' + StartDateS);
        system.debug('EndDateS' + EndDateS);
        system.debug('EnjiID' + EnjiID);
        return [SELECT Id,AbsenceReason__c,BusBackNotUse__c,BusGoingNotUse__c,OutsideFast__c,Outside__c,AbsentSchedule__c ,Contact__r.Id,Contact__r.kana__c,Date__c FROM KindergartenDiary__c WHERE Contact__r.Id =:EnjiID AND Date__c >= :StartDateS AND Date__c <= :EndDateS];
    }
    
    /* ------------------------------------------------
        overtimeReservation:園児日誌を一括upsert
    ------------------------------------------------ */
    @AuraEnabled
    public static String upsertKindergartenDiary(List<KindergartenDiary__c> upsertList) {
        system.debug('これこれupsertList');
        system.debug(upsertList);
        return 'あああ';
    }




    /* ------------------------------------------------
        staffAttendanceMenu03:要録一覧を取得
    ------------------------------------------------ */
    @AuraEnabled
    public static List<ImportantNotes__c> findImportantNotes2(String searchValue,String searchDate,String searchGroup) {
        //!!!!!　年度と会計年度をあわせる処理を加える!!!!!!!!
        // 基準日の設定（本日）
        Date TDY =Date.valueOf(searchDate);
        // 会計年度期首月を取得
        Organization organization = [SELECT Id, Name,FiscalYearStartMonth FROM Organization LIMIT 1];
        // 会計年度期首月日を設定
        integer StartFYSM = organization.FiscalYearStartMonth;
        date StartDate = date.newInstance(TDY.year(), StartFYSM, 1);
        // 会計年度期末月日を設定
        date EndDate = (StartDate.addYears(1)).addDays(-1);
        //期末より月が小さかったらマイナス1年 
        if(EndDate.month() >=TDY.month()){
            TDY = TDY.addYears(-1); 
        }
        // 文字列に変化して頭4文字でYYYYを取得
        String searchYears = TDY.format();
        searchYears = searchYears.left(4);
        
        if(searchGroup == 'bus'){
            return [SELECT Id, Name ,PickUpTimeText__c,DropOffText__c,Contact__r.Id, Contact__r.kana__c , Class__c FROM ImportantNotes__c WHERE Contact__r.PassageRoute__c =: searchValue AND FiscalYear__c =:searchYears ORDER BY PickUpTime__c ASC NULLS LAST];
        }
        if(searchGroup == 'class'){
            return [SELECT Id, Name ,PickUpTimeText__c,DropOffText__c,Contact__r.Id, Contact__r.kana__c , Class__c FROM ImportantNotes__c WHERE Class__c =: searchValue AND FiscalYear__c =:searchYears ORDER BY DisplayOrder__c ASC NULLS LAST];
        }else{
            return new List<ImportantNotes__c>();
        }

        /* 別パターンの記述
            List<ImportantNotes__c> ImportantNoteList = new List<ImportantNotes__c> ();
            ImportantNoteList = [SELECT Id, Name ,Contact__r.Id, Contact__r.kana__c , Class__c,Remarks__c FROM ImportantNotes__c WHERE Class__c =: searchKey AND FiscalYear__c =:searchYear];
            return ImportantNoteList;
        */

    }

    /* ------------------------------------------------
        staffAttendanceMenu03:園児日報一覧を取得
    ------------------------------------------------ */
    @AuraEnabled
    public static List<KindergartenDiary__c> findKindergartenDiary(String searchDate) {
        Date myDate = Date.valueOf(searchDate);
        system.debug(searchDate);
        return [SELECT Id,AbsenceReason__c,AttendanceSchedule__c,BusBackNotUse__c,BusGoingNotUse__c,Contact__r.Id,Contact__r.kana__c,Date__c , AttendanceTime__c , AttendingSchool__c ,AbsentSchedule__c , attendingSchoolTime__c , GoingBack__c , GoingBackTime__c FROM KindergartenDiary__c WHERE Date__c =:myDate];

        /* 別パターンの記述
            List<KindergartenDiary__c> KindergartenDiaryList = new List<KindergartenDiary__c>();
            KindergartenDiaryList = [SELECT Id,AttendanceSchedule__c ,Contact__r.Id,Contact__r.kana__c FROM KindergartenDiary__c WHERE Date__c =:myDate];
            return KindergartenDiaryList;
        */

    }
    
}