force-app/main/default/objects/Contact/fields/Memo__c.field-meta.xml
<CustomField>
    <fullName>Memo__c</fullName>
    <label>メモ</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PhotoURL__c.field-meta.xml
<CustomField>
    <fullName>PhotoURL__c</fullName>
    <label>写真URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ContactController.cls
public with sharing class ContactController {

    @AuraEnabled(cacheable=true)
    public static List<Contact> getContactList() {
        return [SELECT Id, FirstName, LastName, Title, Phone, Email,Name, Memo__c FROM Contact LIMIT 10];
    }

    @AuraEnabled(cacheable=true)
    public static List<Contact> findContacts(String searchKey) {
        if (String.isBlank(searchKey)) {
            return new List<Contact>();
        }
        String key = '%' + searchKey + '%';
        return [SELECT Id, Name, Memo__c, PhotoURL__c FROM Contact WHERE Name LIKE :key  LIMIT 10];
    }



}