force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>性別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>男子</fullName>
            </value>
            <value>
                <fullName>女子</fullName>
            </value>
            <value>
                <fullName>男</fullName>
            </value>
            <value>
                <fullName>女</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/ImportantNotes__c.object-meta.xml
<CustomObject>
    <label>要録情報</label>
    <nameField>
        <displayFormat>IN{YYYY}/{MM}-{000}</displayFormat>
        <label>要録情報名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ImportantNotes__c/fields/AttendanceDays__c.field-meta.xml
<CustomField>
    <fullName>AttendanceDays__c</fullName>
    <label>出席日数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <formula>Contact__r.Birthdate</formula>
    <label>誕生日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>園児</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>要録情報</relationshipLabel>
    <relationshipName>ImportantNotes_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/ContactName__c.field-meta.xml
<CustomField>
    <fullName>ContactName__c</fullName>
    <formula>Contact__r.kana__c</formula>
    <label>園児名</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>FiscalYear__c</fullName>
    <label>年度</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/GradePointEmphasis__c.field-meta.xml
<CustomField>
    <fullName>GradePointEmphasis__c</fullName>
    <label>学年の重点</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/JapaneseCalendar__c.field-meta.xml
<CustomField>
    <fullName>JapaneseCalendar__c</fullName>
    <formula>CASE( FiscalYear__c ,
&quot;2010&quot;, &quot;平成 22 年&quot;,
&quot;2011&quot;, &quot;平成 23 年&quot;,
&quot;2012&quot;, &quot;平成 24 年&quot;,
&quot;2013&quot;, &quot;平成 25 年&quot;,
&quot;2014&quot;, &quot;平成 26 年&quot;,
&quot;2015&quot;, &quot;平成 27 年&quot;,
&quot;2016&quot;, &quot;平成 28 年&quot;,
&quot;2017&quot;, &quot;平成 29 年&quot;,
&quot;2018&quot;, &quot;平成 30 年&quot;,
&quot;2019&quot;, &quot;令和 元 年&quot;,
&quot;2020&quot;, &quot;令和 2 年&quot;,
&quot;2021&quot;, &quot;令和 3 年&quot;,
&quot;2022&quot;, &quot;令和 4 年&quot;,
&quot;2023&quot;, &quot;令和 5 年&quot;,
&quot;2024&quot;, &quot;令和 6 年&quot;,
&quot;2025&quot;, &quot;令和 7 年&quot;,
&quot;2026&quot;, &quot;令和 8 年&quot;,
&quot;2027&quot;, &quot;令和 9 年&quot;,
&quot;2028&quot;, &quot;令和 10 年&quot;,
&quot;2029&quot;, &quot;令和 11 年&quot;,
&quot;2030&quot;, &quot;令和 12 年&quot;,
&quot;2031&quot;, &quot;令和 13 年&quot;,
&quot;2032&quot;, &quot;令和 14 年&quot;,
&quot;2033&quot;, &quot;令和 15 年&quot;,
&quot;&quot;)</formula>
    <label>和暦</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/PersonalEmphasis__c.field-meta.xml
<CustomField>
    <fullName>PersonalEmphasis__c</fullName>
    <label>個人の重点</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/ReferenceItems__c.field-meta.xml
<CustomField>
    <fullName>ReferenceItems__c</fullName>
    <label>参考となる事項</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>備考</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ImportantNotes__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <formula>TEXT(Contact__r.Sex__c)</formula>
    <label>性別</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Yourokuget.cls
public class Yourokuget {

    // property
    public String message {
        get {
            return '・テスト　０１ああ<br />あああああああ';
        }
        set;
    }

    // getter
    public String getMessage2() {
        return 'Good bye!';
    }

    public List<ImportantNotes__c> getImportantNotes() {
    
        List<ImportantNotes__c> results = Database.query(
            'SELECT Id, ContactName__c, Contact__r.Name, Birthdate__c, Sex__c, JapaneseCalendar__c, GradePointEmphasis__c, PersonalEmphasis__c, ReferenceItems__c, Remarks__c, FiscalYear__c, ChildcareDays__c, AttendanceDays__c ' +
            'FROM ImportantNotes__c ' +
            'ORDER BY FiscalYear__c  DESC ' +
            'LIMIT 6'
        );
        return results;
    }
}